#!/usr/bin/env python3
"""
Generate docs/design/companies-roster.md from career-ops/portals.yml.

Per design plan §4.6: read-only, auto-generated companion to portals.yml.
Markdown table sorted by rank ascending.
"""
import yaml
from datetime import datetime, timezone
from pathlib import Path

SRC = Path('career-ops/portals.yml')
DST = Path('docs/design/companies-roster.md')

with open(SRC, encoding='utf-8') as f:
    data = yaml.safe_load(f)

companies = sorted(data['tracked_companies'], key=lambda c: c.get('rank', 9999))

total = len(companies)
enabled_count = sum(1 for c in companies if c.get('enabled', True))
disabled_count = total - enabled_count
updated = datetime.now(timezone.utc).astimezone().isoformat(timespec='seconds')

lines = [
    '---',
    'status: active',
    'type: design-artifact',
    'owner: claude',
    f'last-updated: {updated}',
    'read-if: "you need the generated live roster from career-ops/portals.yml"',
    'skip-if: "status != active"',
    'related:',
    '  - career-ops/portals.yml',
    '  - docs/audits/2026-04-30-step0-disabled-company-audit.md',
    '---',
    '',
    '# Companies Roster — `portals.yml` Live State',
    '',
    f'**Source:** `career-ops/portals.yml` (auto-generated by `scripts/generate-companies-roster.py`).',
    '',
    f'**Inventory:** {total} total / {enabled_count} enabled / {disabled_count} disabled with notes.',
    '',
    '> Read-only artifact. Do not edit directly. Re-run the generator after any portals.yml change to regenerate this file. See design plan §4.6.',
    '',
    '| Rank | Name | Category | careers_url | Enabled | Note |',
    '|---:|---|---|---|:---:|---|',
]

for c in companies:
    rank = c.get('rank', '')
    name = c.get('name', '').replace('|', '\\|')
    category = c.get('category', '').replace('|', '\\|')
    url = c.get('careers_url', '')
    enabled = '✓' if c.get('enabled', True) else '✗'
    note = (c.get('note') or '').replace('|', '\\|')
    lines.append(f'| {rank} | {name} | {category} | {url} | {enabled} | {note} |')

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'OK: wrote {DST} with {total} companies ({enabled_count} enabled / {disabled_count} disabled).')
